# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RyujumeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RyujumeApp
pod 'UIColor_Hex_Swift', '~> 5.1.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 5.0.0-beta.5'
pod 'TextFieldEffects'
pod 'SwiftyPickerPopover'

  target 'RyujumeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
